### ISSUE TITLE
e -nw could not get terminal name

### ISSUE THREAD

**Issue by jgarte** [pflanze/chj-rustbin#1]
This works:

```sh
$ emacsclient -nw
```

But this doesn't on my setup:

```
$ e -nw
can't currently deal with options, falling back to single emacsclient call (not opening a separate frame per file)
/home/jgart/.guix-profile/bin/emacsclient: could not get terminal name
Error: command ended with error exit code 1: ["emacsclient", "-c", "-nw"]
```

`systemctl status`

![image](https://github.com/pflanze/chj-rustbin/assets/47760695/b7a7784f-4706-409c-8419-427f132bdc19)

![image](https://github.com/pflanze/chj-rustbin/assets/47760695/50b45d30-2112-401a-8480-2333897e0225)

WDYT

**Comment by pflanze** [comment]
Forgot to close this. AFAIK this has been solved, feel free to re-open if not.
